#!/bin/bash
#SBATCH --job-name=dkb_conv
#SBATCH -t 3-00:00:00
#SBATCH -p max_120_hours
#SBATCH -n 24
#SBATCH -w scud

hostname
echo $(date -u)
branch=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch is: \"$branch\""
export OMP_NUM_THREADS=$SLURM_TASKS_PER_NODE

# Parameters
eta_min=0.1
eta_max=0.19
eta_step=0.01

# Loop over r values
eta=$eta_min
while (( $(echo "$eta <= $eta_max" | bc -l) )); do
    echo "Running with eta_slp=$eta"
    python3 run_experiment.py with eta_slp=$eta
    eta=$(echo "$eta + $eta_step" | bc -l)
done

