#!/bin/bash
#SBATCH --job-name=h2p_nkb
#SBATCH -t 3-00:00:00
#SBATCH -p max_120_hours
#SBATCH -n 64
#SBATCH -w roland

hostname
echo $(date -u)
branch=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch is: \"$branch\""
export OMP_NUM_THREADS=$SLURM_TASKS_PER_NODE

python3 run_experiment.py with n=14 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=16 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=18 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=20 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=24 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=28 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=32 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=36 ximax=20 eta_slp=0.029 d=5
python3 run_experiment.py with n=40 ximax=20 eta_slp=0.029 d=5
# python3 run_experiment.py with n=44 ximax=20 eta_slp=0.029 d=5
# python3 run_experiment.py with n=48 ximax=20 eta_slp=0.029 d=5
# python3 run_experiment.py with n=52 ximax=20 eta_slp=0.029 d=5
