#!/bin/bash
#SBATCH --job-name=dkb_conv
#SBATCH -t 3-00:00:00
#SBATCH -p max_120_hours
#SBATCH -n 24
#SBATCH -w scud

hostname
echo $(date -u)
branch=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch is: \"$branch\""
export OMP_NUM_THREADS=$SLURM_TASKS_PER_NODE

python3 run_experiment.py with Z1=90 Z2=90 n=26 R=1.11e-2 ximax=15 eta_slp=0.029
