#!/bin/bash
#SBATCH --job-name=h2+-nkb
#SBATCH -t 3-00:00:00
#SBATCH -p max_120_hours
#SBATCH -n 24
#SBATCH -w sam

hostname
echo $(date -u)
branch=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch is: \"$branch\""
export OMP_NUM_THREADS=$SLURM_TASKS_PER_NODE

python3 run_opti_optuna.py $SLURM_TASKS_PER_NODE
