#!/bin/bash
#SBATCH --job-name=dkb_conv
#SBATCH -t 3-00:00:00
#SBATCH -p max_120_hours
#SBATCH -n 24
#SBATCH -w scud

hostname
echo $(date -u)
branch=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch is: \"$branch\""
export OMP_NUM_THREADS=$SLURM_TASKS_PER_NODE
make main.out
#time valgrind --leak-check=yes ./main.out
time ./main.out < input.dat
source ~/.bashrc
push "Computation Finish on branch \"$branch\" in directory \"$(pwd)\""
