#!/bin/bash
#SBATCH --job-name=h2p_nkb
#SBATCH -t infinite
#SBATCH -p normal
#SBATCH -n 2
#SBATCH -w babur

hostname
echo $(date -u)
branch=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch is: \"$branch\""
export OMP_NUM_THREADS=$SLURM_TASKS_PER_NODE

python3 run_experiment.py with n=20 d=10 ximax=30 eta_slp=0.88923 xi_slp=9.82222 -c "evol eta regime best"
